[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
capstone_harshit = "CjPe2KvPS1zrjudwdtWbUN9bxYnKaz96g9QiqSd8zPed"

# [programs.devnet]
# capstone_harshit = "CjPe2KvPS1zrjudwdtWbUN9bxYnKaz96g9QiqSd8zPed"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/titan/Desktop/capstone-harshit/harshit.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"